# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_AB_test_B
# # exit
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_B_test_A
# # exit 
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_gyro/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_AB_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/acce_mage/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_AB_test_B
python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_B_test_A
python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_A_test_B
python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A30_B0_AB0_label_A_test_A
python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A10_B10_AB30_label_B_test_A
python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/split_ae/gyro_mage/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/mhealth/ablation/acce_gyro/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/mhealth/ablation/acce_gyro/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/mhealth/ablation/acce_mage/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/mhealth/ablation/acce_mage/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/mhealth/ablation/gyro_mage/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/mhealth/ablation/gyro_mage/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/opp/ablation/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/opp/ablation/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/opp/dccae/A0_B0_AB30_label_AB_test_B
# python3 src/main.py --config ./config/opp/dccae/A0_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/opp/dccae/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/opp/dccae/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/opp/dccae/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/opp/dccae/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/opp/dccae/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/opp/dccae/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/opp/dccae/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/opp/dccae/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/opp/dccae/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/opp/dccae/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/rgb_depth/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_AB_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_depth/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_AB_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A30_B0_AB0_label_A_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A10_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A10_B0_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B30_AB0_label_B_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B10_AB30_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A0_B0_AB30_label_AB_test_A
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A10_B10_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/split_ae/acce_rgb/A10_B0_AB30_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/ablation/rgb_depth/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/ablation/rgb_depth/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/ablation/acce_depth/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/ablation/acce_depth/A30_B30_AB0_label_A_test_B
# python3 src/main.py --config ./config/ur_fall/ablation/acce_rgb/A30_B30_AB0_label_B_test_A
# python3 src/main.py --config ./config/ur_fall/ablation/acce_rgb/A30_B30_AB0_label_A_test_B
